# Generated by Django 5.1.7 on 2025-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_ai_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedroundup',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='hashnode_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
