# Generated by Django 5.1.7 on 2025-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_publishedroundup_cover_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedroundup',
            name='hashnode_id',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='url',
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='hashnode_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
