# Generated by Django 5.1.7 on 2025-03-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsroundup'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroundup',
            name='devto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
