# Generated by Django 5.1.7 on 2025-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsroundup_devto_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsRoundup',
        ),
        migrations.AlterModelOptions(
            name='publishedroundup',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='content',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='hashnode_url',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='language',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='title',
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='devto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='article_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
