# Generated by Django 5.1.7 on 2025-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_newsroundup_alter_publishedroundup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedroundup',
            name='devto_url',
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='platform',
            field=models.CharField(default='Dev.to', max_length=50),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='title',
            field=models.CharField(default='News Roundup', max_length=200),
        ),
        migrations.AddField(
            model_name='publishedroundup',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
