# Generated by Django 5.1.7 on 2025-03-31 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_publishedroundup_devto_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedroundup',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Published roundups'},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Search queries'},
        ),
        migrations.RenameField(
            model_name='publishedroundup',
            old_name='url',
            new_name='hashnode_url',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='publishedroundup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='results_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publishedroundup',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
